### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by KyleAMathews** [petehunt/react-raf-batching#3]
I understand you require this somewhere and override the core batching strategy... but how?

**Comment by capaj** [comment]
@KyleAMathews good find.

**Comment by thebigredgeek** [comment]
Just look at the main file...

**Comment by DelvarWorld** [comment]
@KyleAMathews @Tvaroh @capaj Made a PR for it, I think it benefits the whole JS community if we're all proactive about adding easy changes to repositories.

@datarhyne Please consider what it's like for a newcomer to approach a new technology :) Defending purposely not-documenting a project moves us backwards...
